---
language: "python"
python:
  - "3.7"

# Install python packages for Ansible and associated collections.
install:
  - "pip install -r requirements.txt"
  - "ansible-galaxy collection install -r requirements.yml"

# Because these scripts are for training, just do a quick lint.
script:
  - "find . -name '*.yml' | xargs yamllint -s"
  - "find . -name '*playbook.yml' | xargs ansible-lint -v"
...
