---
- name: "Collect information from router and print it"
  hosts: "routers"
  tasks:
    - name: "Run commands on router"
      cisco.ios.ios_command:
        commands: "{{ commands }}"
      register: "cli_output"

    - name: "Print collected output"
      ansible.builtin.debug:
        var: "cli_output.stdout_lines"
...
